version: '3.7'

services:
  adminservice:
    build:
      context: ./AdminService
      dockerfile: Dockerfile
    image: adminservice
    container_name: AdminService-server
    command: npm start
    volumes:
      - ./adminservice/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5003:5003"
    networks:
      - app-network
  authservice:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    image: authservice
    container_name: AuthService
    command: npm start
    volumes:
      - ./authservice/:/usr/src/app
      - /usr/app/node_modules
    ports:
      - "5000:5000"
    networks:
      - app-network
  categoriesservice:
    build:
        context: ./CategoriesService
        dockerfile: Dockerfile
    image: categoriesservice
    container_name: CategoriesService
    command: npm start
    volumes: 
        - ./categoriesservice/:/usr/src/app
        - /usr/app/node_modules
    ports: 
        - "5002:5002"
    networks: 
        - app-network  
  homeservice:
    build:
        context: ./HomesService
        dockerfile: Dockerfile
    image: homesservice
    container_name: HomesService
    command: npm start
    volumes: 
        - ./homesservice/:/usr/app
        - /usr/app/node_modules
    ports:
        - "5004:5004"
    networks: 
        - app-network
  usersservices:
    build:
        context: ./UsersServices
        dockerfile: Dockerfile
    image: usersservices
    container_name: UsersServices
    command: npm start
    volumes: 
        - ./usersservices/:/usr/app
        - /usr/app/node_modules
    ports:
        - "5001:5001"
    networks: 
        - app-network                  



    
networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local